### POST REQUEST 
POST http://localhost:4004/odata/v4/labelservice/deleteMusicians
Content-Type: application/json

{
    "value": ["025bf968-1303-4b7f-bf14-eba299c272cb", "a0310213-64ef-416e-a39a-8a257bcad608"]
}